### ISSUE TITLE
Wrong CWD handling

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-to-cabal#114]
Consider running `dhall-to-cabal foo/bar.dhall`. The input file name could have relative imports, which have to be resolved relative to `foo/`. However, we read the file and then process it totally divorced of that directory information: we'll try to resolve imports relative to the current working directory.

This isn't trivially fixable in dhall-to-cabal: we need some extra API from dhall itself to specify what directory an expression's imports should be resolved relative to.

**Comment by ocharles** [comment]
Actually, it's pretty easy - just parse the absolute path to the file as a Dhall expression itself.

**Comment by quasicomputational** [comment]
Hmm. No guarantee that the file's name is legal in a Dhall expression, though. The other easy hack is to change our CWD, I guess, but that's rude to do in a library.
