### ISSUE TITLE
Cabal 2.4.0.0

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-to-cabal#128]
I think the relevant lines from the changelog are:

* KnownExtension: added new extensions BlockArguments (#5101), NumericUnderscores (#5130, QuantifiedConstraints, and StarIsType.
* buildDepends is removed from PackageDescription. It had long been uselessly hanging about as top-level build-depends already got put into per-component condition trees anyway. Now it's finally been put out of its misery (#4383).
* Added Eta to CompilerFlavor and to known compilers.
* Allow ** wildcards in data-files, extra-source-files and extra-doc-files. These allow a limited form of recursive matching, and require cabal-version: 2.4. (#5284, #3178, et al.)

**Comment by quasicomputational** [comment]
I'll have a look. I'm about 80% sure there's nothing more serious than updating the enums.
