### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-to-cabal#134]
I don't have as much time as I used to for `dhall-to-cabal`, so I'd love to have some people help me out. @quasicomputational and @jneira are obviously choices. Would either of you like commit rights?

**Comment by jneira** [comment]
Wow thanks, it would be a honour for me but I would prefer that there was one reviewer with more experience and knowledge than me 😉

**Comment by ocharles** [comment]
Don't worry, I'll still be reviewing, and would still hope everyone goes through PRs (in fact, it's mandated in this repository anyway - a PR has to be open and successfully build against `master`). But I understand, thanks for the reply!

**Comment by quasicomputational** [comment]
Sure! For the time being I'm probably not going to do any major work (mostly because I think things are in good shape as they are), but I'll definitely chip in with keeping things ticking over with maintenance and the dependency treadmill. Thank you for the offer and I gladly accept it.

**Comment by ocharles** [comment]
@quasicomputational has been added to the team - welcome! If anyone else wants to join, just comment here. I'll close this for now as there are at least two of us who can merge PRs.

**Comment by jneira** [comment]
@ocharles i would like to join, although i think i am not be able to merge substantial pr's for now (although being a collaborator could be useful to upload binaries to releases or merge minor changes, if you agree)

**Comment by ocharles** [comment]
@jneira fine with me!
