### ISSUE TITLE
Release last version (1.3.1.0)

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-to-cabal#139]
@ocharles maybe we could already release the new version to sync with the other dhall projects.

**Comment by ocharles** [comment]
Yep, I'll cut a release now.

**Comment by ocharles** [comment]
This is all ready to go, but unfortunately I can't release Cabal-2.4 packages to Hackage at the moment.

**Comment by jneira** [comment]
Maybe could be useful attach precompiled binaries for linux. windows, etc? I could build a set o win executables in my win 10

**Comment by ocharles** [comment]
Linux binaries tend to be tricky due to dynamic linking (though we could distribute static binaries). 

Happy to have Windows binaries attached.

**Comment by jneira** [comment]
@ocharles shouldnt we change the `cabal-version` in `dhall-to-cabal.cabal` to `2.2` to allow us upload the new versions to hackage and stackage?

**Comment by ocharles** [comment]
[Released!](https://hackage.haskell.org/package/dhall-to-cabal-1.3.1.0)
