### ISSUE TITLE
1.3.1.0 build failure

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-to-cabal#144]
https://matrix.hackage.haskell.org/#/package/dhall-to-cabal

**Comment by quasicomputational** [comment]
I think an incorrect tarball might've got uploaded. Checking out the `1.3.1.0` tag, running `cabal get dhallt-o-cabal-1.3.1.0` to get the version on Hackage, and comparing them with `diff -r` shows that `subExpr` is missing from the Hackage version.

**Comment by ocharles** [comment]
Yea I think I had unstaged changes. Unfortunate!

**Comment by BardurArantsson** [comment]
@ocharles Could you uploading a new version? (With a new version number, I mean.)

I was looking to try it out, but ran into this build failure :(. That doesn't give potential users a good impression :/.

**Comment by ocharles** [comment]
Oh, that's not good! We should have a new release Real Soon Now. But you
can build from Git I believe. Will see what I can do

**Comment by BardurArantsson** [comment]
Thanks! :)
