### ISSUE TITLE
Require Cabal 2.1

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-to-cabal#19]
This is needed for Cabal's pretty printer to actually work. Unfortunately, this isn't out yet.

**Comment by ocharles** [comment]
Cabal skipped a whole major version, but 2.2 is out now. I'll mandate that.

**Comment by quasicomputational** [comment]
I've got a rough version of this ready. Still some bikeshedding to do around the SPDX license stuff; I'll get a PR up in the next few days.

**Comment by ocharles** [comment]
Terrific, thank you!

**Comment by ocharles** [comment]
Fixed in https://github.com/dhall-lang/dhall-to-cabal/commit/05ab27d4427d7542236b3e82d39cb1b9cf3977f8
