### ISSUE TITLE
Possibly remove Guarded?

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-to-cabal#45]
#44 un-exports it from types.dhall, meaning that, if you want to use it, it's got to be imported separately. But it's not a big type anyway; `types.Config -> a` is only a bit longer than `types.Guarded a`, and it's arguably clearer. Maybe it makes more sense to always write it as the former, and to drop `Guarded` as a thing? It made a lot of sense to have `Guarded` when it was a record, but now that conditionals are done implicitly I'm not so sure.

**Comment by ocharles** [comment]
`Guarded` is no more! And it was an easy decision, our hand was forced :)

**Comment by quasicomputational** [comment]
Ah, I meant removing it from the repository entirely (i.e., deleting `Guarded.dhall` and all knock-on mentions of it), not just un-exporting it. #44 was absolutely necessary; I had the bigger, breaking-er change in mind for this issue.
