### ISSUE TITLE
Use defaults in cabal-to-dhall

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-to-cabal#57]
`cabal-to-dhall` generates pretty big output, see, e.g., [this test](https://github.com/quasicomputational/dhall-to-cabal/blob/da6c72d2916d737fb191f52a52b1e204f82816b2/golden-tests/cabal-to-dhall/gh-36.dhall) from #54, where four conditionals lead to 16 mostly-empty `Library` records. If defaults were used, it would look more like [this](https://gist.github.com/quasicomputational/b4b16130726f82b0fbd1ed6260d44340#file-input-dhall), which is a lot less scary.

**Comment by ocharles** [comment]
Yea, I did start to do this - in some places it uses defaults. It's a fair bit of work to do this though, and I was burning out a bit and just wanted to release what I had.

**Comment by quasicomputational** [comment]
Yeah, no worries. It's plenty good enough for a 1.0 as it is, and this should be doable incrementally, if anyone wants to have a whack at bits of it. Depending on how much knowledge gets moved into the code, we might be able to add a `--print-default $TYPE` option and then generate `dhall/defaults/*` with that.
