### ISSUE TITLE
Pretty-print cabal-to-dhall's output

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-to-cabal#58]
`cabal-to-dhall` currently outputs a potentially-large, unformatted blob of Dhall. Considering especially that experimenting with `cabal-to-dhall` could be someone's first taste of Dhall, this is particularly bad UX. We should figure out how to wire up Dhall's pretty-printing to our output.

**Comment by ocharles** [comment]
Yep, that should be pretty simple - https://hackage.haskell.org/package/dhall-1.14.0/docs/Dhall-Pretty.html `prettyExpr` should do the job, and we can just strip annotations.
