### ISSUE TITLE
Remove Union, unionAlt, etc?

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-to-cabal#84]
Using `Union`, `unionAlt`, etc in `CabalToDhall` leads to some cute definitions, but I'm not sure they're pulling their weight. 

Losing warnings about incomplete pattern matches is a pretty big price to pay for some convenience! Also, I think we want to write most (all?) sum types in terms of `prelude.types.*`, rather than the often-much-larger union literals on users.

So I think we should remove these, and write the `InputType`s directly. This can be done incrementally and there's no pressing need to get it done, though.

**Comment by ocharles** [comment]
I'm fine with this. `Union` and `unionAlt` were probably a cute idea that doesn't really add much in practice.
