### ISSUE TITLE
More test cases

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-to-cabal#9]
Currently the golden tests only test this projects cabal file. We should have more test cases. The idea would be to take Cabal files from Hackage, and add them as the golden output. Contributors will need to write a Dhall expression that produces that Cabal file. If that can't be done, then we've found a bug in `dhall-to-cabal`, hurrah!

I would love failing test cases - you don't even have to provide a fix for the failing test.

**Comment by jneira** [comment]
@ocharles hi, it seems the actual tests should be adapted to lib last changes. I've done a pr with the few changes needed for get it: #35. Currently i am trying to make pass the actual test cases.

**Comment by ocharles** [comment]
I think we've done some great work improving test coverage and are test driving things going forward.
